### ISSUE TITLE
Fix code formatting

### ISSUE THREAD

**Issue by klatys** [thewondertwins/learngo#25]
### Issue Type

Fix formatting of code after bullet list item

### Language

Global issue

In Pointers and reference types lesson there is invalid formatting of code after the bullet list item. I fixed it in my PR for Czech translation, will be happy to fix that in all the others as well.
https://github.com/thewondertwins/learngo/blob/master/en/pointersreftypes/README.md
vs
https://github.com/klatys/learngo/tree/cs-init/cs/pointersreftypes/README.md

**Comment by bketelsen** [comment]
I would appreciate codeformatting help!
